(import (scheme base))
(import (c-groveler))

(define (main)
  (let ((g (make-c-groveler)))
    (grovel-c-include g "sys/stat.h")
    (grovel-c-include g "sys/utsname.h")
    (grovel-c-include g "errno.h")
    (grovel-c-include g "sqlite3.h")
    (grovel-c-struct-size g "stat")
    (grovel-c-struct-field-size g "stat" "st_mtime")
    (grovel-c-struct-field-offset g "stat" "st_mtime")
    (grovel-c-struct-field-size g "utsname" "sysname")
    (grovel-c-constant-integer-ifdef g "EADDRINUSE")
    (grovel-c-type-signedness g "char")
    (grovel-c-type-signedness g "pid_t")
    (grovel-c-type-signedness g "size_t")
    (grovel-c-type-size g "pid_t")
    (grovel-c-constant-integer-ifdef g "SQLITE_READONLY")
    (write-string (c-groveler->string g))))

(main)
