(include <archive.h>)

(constant unsigned ARCHIVE_VERSION_NUMBER)
(constant string ARCHIVE_VERSION_ONLY_STRING)
(constant string ARCHIVE_VERSION_STRING)

;;(call-constant string archive_version_string)
;;(call-constant string archive_version_details)

(constant signed ARCHIVE_EOF)
(constant signed ARCHIVE_OK)
(constant signed ARCHIVE_RETRY)
(constant signed ARCHIVE_WARN)
(constant signed ARCHIVE_FAILED)
(constant signed ARCHIVE_FATAL)

(constant unsigned ARCHIVE_FILTER_NONE)
(constant unsigned ARCHIVE_FILTER_GZIP)
(constant unsigned ARCHIVE_FILTER_BZIP2)
(constant unsigned ARCHIVE_FILTER_COMPRESS)
(constant unsigned ARCHIVE_FILTER_PROGRAM)
(constant unsigned ARCHIVE_FILTER_LZMA)
(constant unsigned ARCHIVE_FILTER_XZ)
(constant unsigned ARCHIVE_FILTER_UU)
(constant unsigned ARCHIVE_FILTER_RPM)
(constant unsigned ARCHIVE_FILTER_LZIP)
(constant unsigned ARCHIVE_FILTER_LRZIP)
(constant unsigned ARCHIVE_FILTER_LZOP)
(constant unsigned ARCHIVE_FILTER_GRZIP)
(constant unsigned ARCHIVE_FILTER_LZ4)
(constant unsigned ARCHIVE_FILTER_ZSTD)

(constant unsigned ARCHIVE_FORMAT_BASE_MASK)
(constant unsigned ARCHIVE_FORMAT_CPIO)
(constant unsigned ARCHIVE_FORMAT_CPIO_POSIX)
(constant unsigned ARCHIVE_FORMAT_CPIO_BIN_LE)
(constant unsigned ARCHIVE_FORMAT_CPIO_BIN_BE)
(constant unsigned ARCHIVE_FORMAT_CPIO_SVR4_NOCRC)
(constant unsigned ARCHIVE_FORMAT_CPIO_SVR4_CRC)
(constant unsigned ARCHIVE_FORMAT_CPIO_AFIO_LARGE)
(constant unsigned ARCHIVE_FORMAT_SHAR)
(constant unsigned ARCHIVE_FORMAT_SHAR_BASE)
(constant unsigned ARCHIVE_FORMAT_SHAR_DUMP)
(constant unsigned ARCHIVE_FORMAT_TAR)
(constant unsigned ARCHIVE_FORMAT_TAR_USTAR)
(constant unsigned ARCHIVE_FORMAT_TAR_PAX_INTERCHANGE)
(constant unsigned ARCHIVE_FORMAT_TAR_PAX_RESTRICTED)
(constant unsigned ARCHIVE_FORMAT_TAR_GNUTAR)
(constant unsigned ARCHIVE_FORMAT_ISO9660)
(constant unsigned ARCHIVE_FORMAT_ISO9660_ROCKRIDGE)
(constant unsigned ARCHIVE_FORMAT_ZIP)
(constant unsigned ARCHIVE_FORMAT_EMPTY)
(constant unsigned ARCHIVE_FORMAT_AR)
(constant unsigned ARCHIVE_FORMAT_AR_GNU)
(constant unsigned ARCHIVE_FORMAT_AR_BSD)
(constant unsigned ARCHIVE_FORMAT_MTREE)
(constant unsigned ARCHIVE_FORMAT_RAW)
(constant unsigned ARCHIVE_FORMAT_XAR)
(constant unsigned ARCHIVE_FORMAT_LHA)
(constant unsigned ARCHIVE_FORMAT_CAB)
(constant unsigned ARCHIVE_FORMAT_RAR)
(constant unsigned ARCHIVE_FORMAT_7ZIP)
(constant unsigned ARCHIVE_FORMAT_WARC)
(constant unsigned ARCHIVE_FORMAT_RAR_V5)

(constant unsigned ARCHIVE_READ_FORMAT_CAPS_NONE)
(constant unsigned ARCHIVE_READ_FORMAT_CAPS_ENCRYPT_DATA)
(constant unsigned ARCHIVE_READ_FORMAT_CAPS_ENCRYPT_METADATA)

(constant signed ARCHIVE_READ_FORMAT_ENCRYPTION_UNSUPPORTED)
(constant signed ARCHIVE_READ_FORMAT_ENCRYPTION_DONT_KNOW)
