(include <errno.h>)
(include <string.h>)

;; Highest errno number defined by the OS.
(constant-ifdef signed ELAST)

(constant-ifdef signed E2BIG)
(constant-ifdef signed EACCES)
(constant-ifdef signed EADDRINUSE)
(constant-ifdef signed EADDRNOTAVAIL)
(constant-ifdef signed EADV)
(constant-ifdef signed EAFNOSUPPORT)
(constant-ifdef signed EAGAIN)
(constant-ifdef signed EALREADY)
(constant-ifdef signed EAUTH)
(constant-ifdef signed EBADARCH)
(constant-ifdef signed EBADE)
(constant-ifdef signed EBADEXEC)
(constant-ifdef signed EBADF)
(constant-ifdef signed EBADFD)
(constant-ifdef signed EBADMACHO)
(constant-ifdef signed EBADMSG)
(constant-ifdef signed EBADR)
(constant-ifdef signed EBADRPC)
(constant-ifdef signed EBADRQC)
(constant-ifdef signed EBADSLT)
(constant-ifdef signed EBFONT)
(constant-ifdef signed EBUSY)
(constant-ifdef signed ECANCELED)
(constant-ifdef signed ECAPMODE)
(constant-ifdef signed ECHILD)
(constant-ifdef signed ECHRNG)
(constant-ifdef signed ECOMM)
(constant-ifdef signed ECONNABORTED)
(constant-ifdef signed ECONNREFUSED)
(constant-ifdef signed ECONNRESET)
(constant-ifdef signed EDEADLK)
(constant-ifdef signed EDEADLOCK)
(constant-ifdef signed EDESTADDRREQ)
(constant-ifdef signed EDEVERR)
(constant-ifdef signed EDOM)
(constant-ifdef signed EDOOFUS)
(constant-ifdef signed EDOTDOT)
(constant-ifdef signed EDQUOT)
(constant-ifdef signed EEXIST)
(constant-ifdef signed EFAULT)
(constant-ifdef signed EFBIG)
(constant-ifdef signed EFTYPE)
(constant-ifdef signed EHOSTDOWN)
(constant-ifdef signed EHOSTUNREACH)
(constant-ifdef signed EHWPOISON)
(constant-ifdef signed EIDRM)
(constant-ifdef signed EILSEQ)
(constant-ifdef signed EINPROGRESS)
(constant-ifdef signed EINTEGRITY)
(constant-ifdef signed EINTR)
(constant-ifdef signed EINVAL)
(constant-ifdef signed EIO)
(constant-ifdef signed EIPSEC)
(constant-ifdef signed EISCONN)
(constant-ifdef signed EISDIR)
(constant-ifdef signed EISNAM)
(constant-ifdef signed EKEYEXPIRED)
(constant-ifdef signed EKEYREJECTED)
(constant-ifdef signed EKEYREVOKED)
(constant-ifdef signed EL2HLT)
(constant-ifdef signed EL2NSYNC)
(constant-ifdef signed EL3HLT)
(constant-ifdef signed EL3RST)
(constant-ifdef signed ELIBACC)
(constant-ifdef signed ELIBBAD)
(constant-ifdef signed ELIBEXEC)
(constant-ifdef signed ELIBMAX)
(constant-ifdef signed ELIBSCN)
(constant-ifdef signed ELNRNG)
(constant-ifdef signed ELOCKUNMAPPED)
(constant-ifdef signed ELOOP)
(constant-ifdef signed EMEDIUMTYPE)
(constant-ifdef signed EMFILE)
(constant-ifdef signed EMLINK)
(constant-ifdef signed EMSGSIZE)
(constant-ifdef signed EMULTIHOP)
(constant-ifdef signed ENAMETOOLONG)
(constant-ifdef signed ENAVAIL)
(constant-ifdef signed ENEEDAUTH)
(constant-ifdef signed ENETDOWN)
(constant-ifdef signed ENETRESET)
(constant-ifdef signed ENETUNREACH)
(constant-ifdef signed ENFILE)
(constant-ifdef signed ENOANO)
(constant-ifdef signed ENOATTR)
(constant-ifdef signed ENOBUFS)
(constant-ifdef signed ENOCSI)
(constant-ifdef signed ENODATA)
(constant-ifdef signed ENODEV)
(constant-ifdef signed ENOENT)
(constant-ifdef signed ENOEXEC)
(constant-ifdef signed ENOKEY)
(constant-ifdef signed ENOLCK)
(constant-ifdef signed ENOLINK)
(constant-ifdef signed ENOMEDIUM)
(constant-ifdef signed ENOMEM)
(constant-ifdef signed ENOMSG)
(constant-ifdef signed ENONET)
(constant-ifdef signed ENOPKG)
(constant-ifdef signed ENOPOLICY)
(constant-ifdef signed ENOPROTOOPT)
(constant-ifdef signed ENOSPC)
(constant-ifdef signed ENOSR)
(constant-ifdef signed ENOSTR)
(constant-ifdef signed ENOSYS)
(constant-ifdef signed ENOTACTIVE)
(constant-ifdef signed ENOTBLK)
(constant-ifdef signed ENOTCAPABLE)
(constant-ifdef signed ENOTCONN)
(constant-ifdef signed ENOTDIR)
(constant-ifdef signed ENOTEMPTY)
(constant-ifdef signed ENOTNAM)
(constant-ifdef signed ENOTRECOVERABLE)
(constant-ifdef signed ENOTSOCK)
(constant-ifdef signed ENOTSUP)
(constant-ifdef signed ENOTTY)
(constant-ifdef signed ENOTUNIQ)
(constant-ifdef signed ENXIO)
(constant-ifdef signed EOPNOTSUPP)
(constant-ifdef signed EOVERFLOW)
(constant-ifdef signed EOWNERDEAD)
(constant-ifdef signed EPERM)
(constant-ifdef signed EPFNOSUPPORT)
(constant-ifdef signed EPIPE)
(constant-ifdef signed EPROCLIM)
(constant-ifdef signed EPROCUNAVAIL)
(constant-ifdef signed EPROGMISMATCH)
(constant-ifdef signed EPROGUNAVAIL)
(constant-ifdef signed EPROTO)
(constant-ifdef signed EPROTONOSUPPORT)
(constant-ifdef signed EPROTOTYPE)
(constant-ifdef signed EPWROFF)
(constant-ifdef signed EQFULL)
(constant-ifdef signed ERANGE)
(constant-ifdef signed EREMCHG)
(constant-ifdef signed EREMOTE)
(constant-ifdef signed EREMOTEIO)
(constant-ifdef signed ERESTART)
(constant-ifdef signed ERFKILL)
(constant-ifdef signed EROFS)
(constant-ifdef signed ERPCMISMATCH)
(constant-ifdef signed ESHLIBVERS)
(constant-ifdef signed ESHUTDOWN)
(constant-ifdef signed ESOCKTNOSUPPORT)
(constant-ifdef signed ESPIPE)
(constant-ifdef signed ESRCH)
(constant-ifdef signed ESRMNT)
(constant-ifdef signed ESTALE)
(constant-ifdef signed ESTRPIPE)
(constant-ifdef signed ETIME)
(constant-ifdef signed ETIMEDOUT)
(constant-ifdef signed ETOOMANYREFS)
(constant-ifdef signed ETXTBSY)
(constant-ifdef signed EUCLEAN)
(constant-ifdef signed EUNATCH)
(constant-ifdef signed EUSERS)
(constant-ifdef signed EWOULDBLOCK)
(constant-ifdef signed EXDEV)
(constant-ifdef signed EXFULL)

(call-constant-ifdef string strerror E2BIG)
(call-constant-ifdef string strerror EACCES)
(call-constant-ifdef string strerror EADDRINUSE)
(call-constant-ifdef string strerror EADDRNOTAVAIL)
(call-constant-ifdef string strerror EADV)
(call-constant-ifdef string strerror EAFNOSUPPORT)
(call-constant-ifdef string strerror EAGAIN)
(call-constant-ifdef string strerror EALREADY)
(call-constant-ifdef string strerror EAUTH)
(call-constant-ifdef string strerror EBADARCH)
(call-constant-ifdef string strerror EBADE)
(call-constant-ifdef string strerror EBADEXEC)
(call-constant-ifdef string strerror EBADF)
(call-constant-ifdef string strerror EBADFD)
(call-constant-ifdef string strerror EBADMACHO)
(call-constant-ifdef string strerror EBADMSG)
(call-constant-ifdef string strerror EBADR)
(call-constant-ifdef string strerror EBADRPC)
(call-constant-ifdef string strerror EBADRQC)
(call-constant-ifdef string strerror EBADSLT)
(call-constant-ifdef string strerror EBFONT)
(call-constant-ifdef string strerror EBUSY)
(call-constant-ifdef string strerror ECANCELED)
(call-constant-ifdef string strerror ECAPMODE)
(call-constant-ifdef string strerror ECHILD)
(call-constant-ifdef string strerror ECHRNG)
(call-constant-ifdef string strerror ECOMM)
(call-constant-ifdef string strerror ECONNABORTED)
(call-constant-ifdef string strerror ECONNREFUSED)
(call-constant-ifdef string strerror ECONNRESET)
(call-constant-ifdef string strerror EDEADLK)
(call-constant-ifdef string strerror EDEADLOCK)
(call-constant-ifdef string strerror EDESTADDRREQ)
(call-constant-ifdef string strerror EDEVERR)
(call-constant-ifdef string strerror EDOM)
(call-constant-ifdef string strerror EDOOFUS)
(call-constant-ifdef string strerror EDOTDOT)
(call-constant-ifdef string strerror EDQUOT)
(call-constant-ifdef string strerror EEXIST)
(call-constant-ifdef string strerror EFAULT)
(call-constant-ifdef string strerror EFBIG)
(call-constant-ifdef string strerror EFTYPE)
(call-constant-ifdef string strerror EHOSTDOWN)
(call-constant-ifdef string strerror EHOSTUNREACH)
(call-constant-ifdef string strerror EHWPOISON)
(call-constant-ifdef string strerror EIDRM)
(call-constant-ifdef string strerror EILSEQ)
(call-constant-ifdef string strerror EINPROGRESS)
(call-constant-ifdef string strerror EINTEGRITY)
(call-constant-ifdef string strerror EINTR)
(call-constant-ifdef string strerror EINVAL)
(call-constant-ifdef string strerror EIO)
(call-constant-ifdef string strerror EIPSEC)
(call-constant-ifdef string strerror EISCONN)
(call-constant-ifdef string strerror EISDIR)
(call-constant-ifdef string strerror EISNAM)
(call-constant-ifdef string strerror EKEYEXPIRED)
(call-constant-ifdef string strerror EKEYREJECTED)
(call-constant-ifdef string strerror EKEYREVOKED)
(call-constant-ifdef string strerror EL2HLT)
(call-constant-ifdef string strerror EL2NSYNC)
(call-constant-ifdef string strerror EL3HLT)
(call-constant-ifdef string strerror EL3RST)
(call-constant-ifdef string strerror ELIBACC)
(call-constant-ifdef string strerror ELIBBAD)
(call-constant-ifdef string strerror ELIBEXEC)
(call-constant-ifdef string strerror ELIBMAX)
(call-constant-ifdef string strerror ELIBSCN)
(call-constant-ifdef string strerror ELNRNG)
(call-constant-ifdef string strerror ELOCKUNMAPPED)
(call-constant-ifdef string strerror ELOOP)
(call-constant-ifdef string strerror EMEDIUMTYPE)
(call-constant-ifdef string strerror EMFILE)
(call-constant-ifdef string strerror EMLINK)
(call-constant-ifdef string strerror EMSGSIZE)
(call-constant-ifdef string strerror EMULTIHOP)
(call-constant-ifdef string strerror ENAMETOOLONG)
(call-constant-ifdef string strerror ENAVAIL)
(call-constant-ifdef string strerror ENEEDAUTH)
(call-constant-ifdef string strerror ENETDOWN)
(call-constant-ifdef string strerror ENETRESET)
(call-constant-ifdef string strerror ENETUNREACH)
(call-constant-ifdef string strerror ENFILE)
(call-constant-ifdef string strerror ENOANO)
(call-constant-ifdef string strerror ENOATTR)
(call-constant-ifdef string strerror ENOBUFS)
(call-constant-ifdef string strerror ENOCSI)
(call-constant-ifdef string strerror ENODATA)
(call-constant-ifdef string strerror ENODEV)
(call-constant-ifdef string strerror ENOENT)
(call-constant-ifdef string strerror ENOEXEC)
(call-constant-ifdef string strerror ENOKEY)
(call-constant-ifdef string strerror ENOLCK)
(call-constant-ifdef string strerror ENOLINK)
(call-constant-ifdef string strerror ENOMEDIUM)
(call-constant-ifdef string strerror ENOMEM)
(call-constant-ifdef string strerror ENOMSG)
(call-constant-ifdef string strerror ENONET)
(call-constant-ifdef string strerror ENOPKG)
(call-constant-ifdef string strerror ENOPOLICY)
(call-constant-ifdef string strerror ENOPROTOOPT)
(call-constant-ifdef string strerror ENOSPC)
(call-constant-ifdef string strerror ENOSR)
(call-constant-ifdef string strerror ENOSTR)
(call-constant-ifdef string strerror ENOSYS)
(call-constant-ifdef string strerror ENOTACTIVE)
(call-constant-ifdef string strerror ENOTBLK)
(call-constant-ifdef string strerror ENOTCAPABLE)
(call-constant-ifdef string strerror ENOTCONN)
(call-constant-ifdef string strerror ENOTDIR)
(call-constant-ifdef string strerror ENOTEMPTY)
(call-constant-ifdef string strerror ENOTNAM)
(call-constant-ifdef string strerror ENOTRECOVERABLE)
(call-constant-ifdef string strerror ENOTSOCK)
(call-constant-ifdef string strerror ENOTSUP)
(call-constant-ifdef string strerror ENOTTY)
(call-constant-ifdef string strerror ENOTUNIQ)
(call-constant-ifdef string strerror ENXIO)
(call-constant-ifdef string strerror EOPNOTSUPP)
(call-constant-ifdef string strerror EOVERFLOW)
(call-constant-ifdef string strerror EOWNERDEAD)
(call-constant-ifdef string strerror EPERM)
(call-constant-ifdef string strerror EPFNOSUPPORT)
(call-constant-ifdef string strerror EPIPE)
(call-constant-ifdef string strerror EPROCLIM)
(call-constant-ifdef string strerror EPROCUNAVAIL)
(call-constant-ifdef string strerror EPROGMISMATCH)
(call-constant-ifdef string strerror EPROGUNAVAIL)
(call-constant-ifdef string strerror EPROTO)
(call-constant-ifdef string strerror EPROTONOSUPPORT)
(call-constant-ifdef string strerror EPROTOTYPE)
(call-constant-ifdef string strerror EPWROFF)
(call-constant-ifdef string strerror EQFULL)
(call-constant-ifdef string strerror ERANGE)
(call-constant-ifdef string strerror EREMCHG)
(call-constant-ifdef string strerror EREMOTE)
(call-constant-ifdef string strerror EREMOTEIO)
(call-constant-ifdef string strerror ERESTART)
(call-constant-ifdef string strerror ERFKILL)
(call-constant-ifdef string strerror EROFS)
(call-constant-ifdef string strerror ERPCMISMATCH)
(call-constant-ifdef string strerror ESHLIBVERS)
(call-constant-ifdef string strerror ESHUTDOWN)
(call-constant-ifdef string strerror ESOCKTNOSUPPORT)
(call-constant-ifdef string strerror ESPIPE)
(call-constant-ifdef string strerror ESRCH)
(call-constant-ifdef string strerror ESRMNT)
(call-constant-ifdef string strerror ESTALE)
(call-constant-ifdef string strerror ESTRPIPE)
(call-constant-ifdef string strerror ETIME)
(call-constant-ifdef string strerror ETIMEDOUT)
(call-constant-ifdef string strerror ETOOMANYREFS)
(call-constant-ifdef string strerror ETXTBSY)
(call-constant-ifdef string strerror EUCLEAN)
(call-constant-ifdef string strerror EUNATCH)
(call-constant-ifdef string strerror EUSERS)
(call-constant-ifdef string strerror EWOULDBLOCK)
(call-constant-ifdef string strerror EXDEV)
(call-constant-ifdef string strerror EXFULL)
