(constant EAI_AGAIN 2)
(constant EAI_BADFLAGS 3)
(constant EAI_FAIL 4)
(constant EAI_FAMILY 5)
(constant EAI_MEMORY 6)
(constant EAI_NONAME 8)
(constant EAI_OVERFLOW 14)
(constant EAI_SERVICE 9)
(constant EAI_SOCKTYPE 10)
(constant EAI_SYSTEM 11)
(call-constant gai_strerror EAI_AGAIN "Temporary failure in name resolution")
(call-constant gai_strerror EAI_BADFLAGS "Invalid value for ai_flags")
(call-constant gai_strerror EAI_FAIL "Non-recoverable failure in name resolution")
(call-constant gai_strerror EAI_FAMILY "ai_family not supported")
(call-constant gai_strerror EAI_MEMORY "Memory allocation failure")
(call-constant gai_strerror EAI_NONAME "nodename nor servname provided, or not known")
(call-constant gai_strerror EAI_OVERFLOW "argument buffer overflow")
(call-constant gai_strerror EAI_SERVICE "servname not supported for ai_socktype")
(call-constant gai_strerror EAI_SOCKTYPE "ai_socktype not supported")
(call-constant gai_strerror EAI_SYSTEM "System error")
(constant EAI_MAX 15)
(constant EAI_BADHINTS 12)
(constant EAI_PROTOCOL 13)
(call-constant gai_strerror EAI_MAX "Unknown error")
(call-constant gai_strerror EAI_BADHINTS "Bad hints")
(call-constant gai_strerror EAI_PROTOCOL "ai_protocol not supported")
(constant HOST_NOT_FOUND 1)
(constant NETDB_INTERNAL -1)
(constant NETDB_SUCCESS 0)
(constant NO_ADDRESS 4)
(constant NO_DATA 4)
(constant NO_RECOVERY 3)
(constant TRY_AGAIN 2)
