(type-size struct-stat 144)
(slot-offs struct-stat st_dev 0)
(slot-size struct-stat st_dev 4)
(slot-offs struct-stat st_ino 8)
(slot-size struct-stat st_ino 8)
(slot-offs struct-stat st_mode 4)
(slot-size struct-stat st_mode 2)
(slot-offs struct-stat st_nlink 6)
(slot-size struct-stat st_nlink 2)
(slot-offs struct-stat st_uid 16)
(slot-size struct-stat st_uid 4)
(slot-offs struct-stat st_gid 20)
(slot-size struct-stat st_gid 4)
(slot-offs struct-stat st_rdev 24)
(slot-size struct-stat st_rdev 4)
(slot-offs struct-stat st_size 96)
(slot-size struct-stat st_size 8)
(slot-offs struct-stat st_blksize 112)
(slot-size struct-stat st_blksize 4)
(slot-offs struct-stat st_blocks 104)
(slot-size struct-stat st_blocks 8)
(constant S_IFMT 61440)
(constant S_IFBLK 24576)
(constant S_IFCHR 8192)
(constant S_IFIFO 4096)
(constant S_IFREG 32768)
(constant S_IFDIR 16384)
(constant S_IFLNK 40960)
(constant S_IFSOCK 49152)
