(type-size struct-utsname 1280)
(slot-offs struct-utsname sysname 0)
(slot-size struct-utsname sysname 256)
(slot-offs struct-utsname nodename 256)
(slot-size struct-utsname nodename 256)
(slot-offs struct-utsname release 512)
(slot-size struct-utsname release 256)
(slot-offs struct-utsname version 768)
(slot-size struct-utsname version 256)
(slot-offs struct-utsname machine 1024)
(slot-size struct-utsname machine 256)
