(include <fcntl.h>)

(constant signed F_DUPFD)
(constant signed F_DUPFD_CLOEXEC)
(constant signed F_GETFD)
(constant signed F_SETFD)
(constant signed F_GETFL)
(constant signed F_SETFL)
(constant signed F_GETLK)
(constant signed F_SETLK)
(constant signed F_SETLKW)
(constant signed F_GETOWN)
(constant signed F_SETOWN)

(constant signed FD_CLOEXEC)

(constant signed F_RDLCK)
(constant signed F_UNLCK)
(constant signed F_WRLCK)

(constant signed SEEK_CUR)
(constant signed SEEK_END)
(constant signed SEEK_SET)

(constant signed O_ACCMODE)
(constant signed O_APPEND)
(constant signed O_CLOEXEC)
(constant signed O_CREAT)
(constant signed O_DIRECTORY)
(constant signed O_DSYNC)
(constant signed O_EXCL)
(constant signed O_NOCTTY)
(constant signed O_NOFOLLOW)
(constant signed O_NONBLOCK)
(constant signed O_RDONLY)
(constant signed O_RDWR)
(constant signed O_SYNC)
(constant signed O_TRUNC)
(constant signed O_WRONLY)

(constant-ifdef signed O_EXEC)
(constant-ifdef signed O_RSYNC)
(constant-ifdef signed O_SEARCH)
(constant-ifdef signed O_TTY_INIT)

(constant signed AT_EACCESS)
(constant signed AT_FDCWD)
(constant signed AT_REMOVEDIR)
(constant signed AT_SYMLINK_FOLLOW)
(constant signed AT_SYMLINK_NOFOLLOW)

(constant-ifdef signed POSIX_FADV_DONTNEED)
(constant-ifdef signed POSIX_FADV_NOREUSE)
(constant-ifdef signed POSIX_FADV_NORMAL)
(constant-ifdef signed POSIX_FADV_RANDOM)
(constant-ifdef signed POSIX_FADV_SEQUENTIAL)
(constant-ifdef signed POSIX_FADV_WILLNEED)
