(include <sqlite3.h>)

(constant signed SQLITE_ABORT_ROLLBACK)
(constant signed SQLITE_AUTH_USER)
(constant signed SQLITE_BUSY_RECOVERY)
(constant signed SQLITE_BUSY_SNAPSHOT)
(constant signed SQLITE_CANTOPEN_CONVPATH)
(constant signed SQLITE_CANTOPEN_DIRTYWAL)
(constant signed SQLITE_CANTOPEN_FULLPATH)
(constant signed SQLITE_CANTOPEN_ISDIR)
(constant signed SQLITE_CANTOPEN_NOTEMPDIR)
(constant signed SQLITE_CONSTRAINT_CHECK)
(constant signed SQLITE_CONSTRAINT_COMMITHOOK)
(constant signed SQLITE_CONSTRAINT_FOREIGNKEY)
(constant signed SQLITE_CONSTRAINT_FUNCTION)
(constant signed SQLITE_CONSTRAINT_NOTNULL)
(constant signed SQLITE_CONSTRAINT_PRIMARYKEY)
(constant signed SQLITE_CONSTRAINT_ROWID)
(constant signed SQLITE_CONSTRAINT_TRIGGER)
(constant signed SQLITE_CONSTRAINT_UNIQUE)
(constant signed SQLITE_CONSTRAINT_VTAB)
(constant signed SQLITE_CORRUPT_SEQUENCE)
(constant signed SQLITE_CORRUPT_VTAB)
(constant signed SQLITE_ERROR_MISSING_COLLSEQ)
(constant signed SQLITE_ERROR_RETRY)
(constant signed SQLITE_ERROR_SNAPSHOT)
(constant signed SQLITE_IOERR_ACCESS)
(constant signed SQLITE_IOERR_AUTH)
(constant signed SQLITE_IOERR_BEGIN_ATOMIC)
(constant signed SQLITE_IOERR_BLOCKED)
(constant signed SQLITE_IOERR_CHECKRESERVEDLOCK)
(constant signed SQLITE_IOERR_CLOSE)
(constant signed SQLITE_IOERR_COMMIT_ATOMIC)
(constant signed SQLITE_IOERR_CONVPATH)
(constant signed SQLITE_IOERR_DELETE)
(constant signed SQLITE_IOERR_DELETE_NOENT)
(constant signed SQLITE_IOERR_DIR_CLOSE)
(constant signed SQLITE_IOERR_DIR_FSYNC)
(constant signed SQLITE_IOERR_FSTAT)
(constant signed SQLITE_IOERR_FSYNC)
(constant signed SQLITE_IOERR_GETTEMPPATH)
(constant signed SQLITE_IOERR_LOCK)
(constant signed SQLITE_IOERR_MMAP)
(constant signed SQLITE_IOERR_NOMEM)
(constant signed SQLITE_IOERR_RDLOCK)
(constant signed SQLITE_IOERR_READ)
(constant signed SQLITE_IOERR_ROLLBACK_ATOMIC)
(constant signed SQLITE_IOERR_SEEK)
(constant signed SQLITE_IOERR_SHMLOCK)
(constant signed SQLITE_IOERR_SHMMAP)
(constant signed SQLITE_IOERR_SHMOPEN)
(constant signed SQLITE_IOERR_SHMSIZE)
(constant signed SQLITE_IOERR_SHORT_READ)
(constant signed SQLITE_IOERR_TRUNCATE)
(constant signed SQLITE_IOERR_UNLOCK)
(constant signed SQLITE_IOERR_VNODE)
(constant signed SQLITE_IOERR_WRITE)
(constant signed SQLITE_LOCKED_SHAREDCACHE)
(constant signed SQLITE_LOCKED_VTAB)
(constant signed SQLITE_NOTICE_RECOVER_ROLLBACK)
(constant signed SQLITE_NOTICE_RECOVER_WAL)
(constant signed SQLITE_OK_LOAD_PERMANENTLY)
(constant signed SQLITE_READONLY_CANTINIT)
(constant signed SQLITE_READONLY_CANTLOCK)
(constant signed SQLITE_READONLY_DBMOVED)
(constant signed SQLITE_READONLY_DIRECTORY)
(constant signed SQLITE_READONLY_RECOVERY)
(constant signed SQLITE_READONLY_ROLLBACK)
(constant signed SQLITE_WARNING_AUTOINDEX)

(constant-ifdef signed SQLITE_BUSY_TIMEOUT)
(constant-ifdef signed SQLITE_CANTOPEN_SYMLINK)
(constant-ifdef signed SQLITE_CONSTRAINT_PINNED)
(constant-ifdef signed SQLITE_CORRUPT_INDEX)
(constant-ifdef signed SQLITE_IOERR_DATA)
(constant-ifdef signed SQLITE_OK_SYMLINK)

(call-constant string sqlite3_errstr SQLITE_ABORT_ROLLBACK)
(call-constant string sqlite3_errstr SQLITE_AUTH_USER)
(call-constant string sqlite3_errstr SQLITE_BUSY_RECOVERY)
(call-constant string sqlite3_errstr SQLITE_BUSY_SNAPSHOT)
(call-constant string sqlite3_errstr SQLITE_CANTOPEN_CONVPATH)
(call-constant string sqlite3_errstr SQLITE_CANTOPEN_DIRTYWAL)
(call-constant string sqlite3_errstr SQLITE_CANTOPEN_FULLPATH)
(call-constant string sqlite3_errstr SQLITE_CANTOPEN_ISDIR)
(call-constant string sqlite3_errstr SQLITE_CANTOPEN_NOTEMPDIR)
(call-constant string sqlite3_errstr SQLITE_CONSTRAINT_CHECK)
(call-constant string sqlite3_errstr SQLITE_CONSTRAINT_COMMITHOOK)
(call-constant string sqlite3_errstr SQLITE_CONSTRAINT_FOREIGNKEY)
(call-constant string sqlite3_errstr SQLITE_CONSTRAINT_FUNCTION)
(call-constant string sqlite3_errstr SQLITE_CONSTRAINT_NOTNULL)
(call-constant string sqlite3_errstr SQLITE_CONSTRAINT_PRIMARYKEY)
(call-constant string sqlite3_errstr SQLITE_CONSTRAINT_ROWID)
(call-constant string sqlite3_errstr SQLITE_CONSTRAINT_TRIGGER)
(call-constant string sqlite3_errstr SQLITE_CONSTRAINT_UNIQUE)
(call-constant string sqlite3_errstr SQLITE_CONSTRAINT_VTAB)
(call-constant string sqlite3_errstr SQLITE_CORRUPT_SEQUENCE)
(call-constant string sqlite3_errstr SQLITE_CORRUPT_VTAB)
(call-constant string sqlite3_errstr SQLITE_ERROR_MISSING_COLLSEQ)
(call-constant string sqlite3_errstr SQLITE_ERROR_RETRY)
(call-constant string sqlite3_errstr SQLITE_ERROR_SNAPSHOT)
(call-constant string sqlite3_errstr SQLITE_IOERR_ACCESS)
(call-constant string sqlite3_errstr SQLITE_IOERR_AUTH)
(call-constant string sqlite3_errstr SQLITE_IOERR_BEGIN_ATOMIC)
(call-constant string sqlite3_errstr SQLITE_IOERR_BLOCKED)
(call-constant string sqlite3_errstr SQLITE_IOERR_CHECKRESERVEDLOCK)
(call-constant string sqlite3_errstr SQLITE_IOERR_CLOSE)
(call-constant string sqlite3_errstr SQLITE_IOERR_COMMIT_ATOMIC)
(call-constant string sqlite3_errstr SQLITE_IOERR_CONVPATH)
(call-constant string sqlite3_errstr SQLITE_IOERR_DELETE)
(call-constant string sqlite3_errstr SQLITE_IOERR_DELETE_NOENT)
(call-constant string sqlite3_errstr SQLITE_IOERR_DIR_CLOSE)
(call-constant string sqlite3_errstr SQLITE_IOERR_DIR_FSYNC)
(call-constant string sqlite3_errstr SQLITE_IOERR_FSTAT)
(call-constant string sqlite3_errstr SQLITE_IOERR_FSYNC)
(call-constant string sqlite3_errstr SQLITE_IOERR_GETTEMPPATH)
(call-constant string sqlite3_errstr SQLITE_IOERR_LOCK)
(call-constant string sqlite3_errstr SQLITE_IOERR_MMAP)
(call-constant string sqlite3_errstr SQLITE_IOERR_NOMEM)
(call-constant string sqlite3_errstr SQLITE_IOERR_RDLOCK)
(call-constant string sqlite3_errstr SQLITE_IOERR_READ)
(call-constant string sqlite3_errstr SQLITE_IOERR_ROLLBACK_ATOMIC)
(call-constant string sqlite3_errstr SQLITE_IOERR_SEEK)
(call-constant string sqlite3_errstr SQLITE_IOERR_SHMLOCK)
(call-constant string sqlite3_errstr SQLITE_IOERR_SHMMAP)
(call-constant string sqlite3_errstr SQLITE_IOERR_SHMOPEN)
(call-constant string sqlite3_errstr SQLITE_IOERR_SHMSIZE)
(call-constant string sqlite3_errstr SQLITE_IOERR_SHORT_READ)
(call-constant string sqlite3_errstr SQLITE_IOERR_TRUNCATE)
(call-constant string sqlite3_errstr SQLITE_IOERR_UNLOCK)
(call-constant string sqlite3_errstr SQLITE_IOERR_VNODE)
(call-constant string sqlite3_errstr SQLITE_IOERR_WRITE)
(call-constant string sqlite3_errstr SQLITE_LOCKED_SHAREDCACHE)
(call-constant string sqlite3_errstr SQLITE_LOCKED_VTAB)
(call-constant string sqlite3_errstr SQLITE_NOTICE_RECOVER_ROLLBACK)
(call-constant string sqlite3_errstr SQLITE_NOTICE_RECOVER_WAL)
(call-constant string sqlite3_errstr SQLITE_OK_LOAD_PERMANENTLY)
(call-constant string sqlite3_errstr SQLITE_READONLY_CANTINIT)
(call-constant string sqlite3_errstr SQLITE_READONLY_CANTLOCK)
(call-constant string sqlite3_errstr SQLITE_READONLY_DBMOVED)
(call-constant string sqlite3_errstr SQLITE_READONLY_DIRECTORY)
(call-constant string sqlite3_errstr SQLITE_READONLY_RECOVERY)
(call-constant string sqlite3_errstr SQLITE_READONLY_ROLLBACK)
(call-constant string sqlite3_errstr SQLITE_WARNING_AUTOINDEX)

(call-constant-ifdef string sqlite3_errstr SQLITE_BUSY_TIMEOUT)
(call-constant-ifdef string sqlite3_errstr SQLITE_CANTOPEN_SYMLINK)
(call-constant-ifdef string sqlite3_errstr SQLITE_CONSTRAINT_PINNED)
(call-constant-ifdef string sqlite3_errstr SQLITE_CORRUPT_INDEX)
(call-constant-ifdef string sqlite3_errstr SQLITE_IOERR_DATA)
(call-constant-ifdef string sqlite3_errstr SQLITE_OK_SYMLINK)
