(constant SQLITE_ABORT_ROLLBACK 516)
(constant SQLITE_AUTH_USER 279)
(constant SQLITE_BUSY_RECOVERY 261)
(constant SQLITE_BUSY_SNAPSHOT 517)
(constant SQLITE_CANTOPEN_CONVPATH 1038)
(constant SQLITE_CANTOPEN_DIRTYWAL 1294)
(constant SQLITE_CANTOPEN_FULLPATH 782)
(constant SQLITE_CANTOPEN_ISDIR 526)
(constant SQLITE_CANTOPEN_NOTEMPDIR 270)
(constant SQLITE_CONSTRAINT_CHECK 275)
(constant SQLITE_CONSTRAINT_COMMITHOOK 531)
(constant SQLITE_CONSTRAINT_FOREIGNKEY 787)
(constant SQLITE_CONSTRAINT_FUNCTION 1043)
(constant SQLITE_CONSTRAINT_NOTNULL 1299)
(constant SQLITE_CONSTRAINT_PRIMARYKEY 1555)
(constant SQLITE_CONSTRAINT_ROWID 2579)
(constant SQLITE_CONSTRAINT_TRIGGER 1811)
(constant SQLITE_CONSTRAINT_UNIQUE 2067)
(constant SQLITE_CONSTRAINT_VTAB 2323)
(constant SQLITE_CORRUPT_SEQUENCE 523)
(constant SQLITE_CORRUPT_VTAB 267)
(constant SQLITE_ERROR_MISSING_COLLSEQ 257)
(constant SQLITE_ERROR_RETRY 513)
(constant SQLITE_ERROR_SNAPSHOT 769)
(constant SQLITE_IOERR_ACCESS 3338)
(constant SQLITE_IOERR_AUTH 7178)
(constant SQLITE_IOERR_BEGIN_ATOMIC 7434)
(constant SQLITE_IOERR_BLOCKED 2826)
(constant SQLITE_IOERR_CHECKRESERVEDLOCK 3594)
(constant SQLITE_IOERR_CLOSE 4106)
(constant SQLITE_IOERR_COMMIT_ATOMIC 7690)
(constant SQLITE_IOERR_CONVPATH 6666)
(constant SQLITE_IOERR_DELETE 2570)
(constant SQLITE_IOERR_DELETE_NOENT 5898)
(constant SQLITE_IOERR_DIR_CLOSE 4362)
(constant SQLITE_IOERR_DIR_FSYNC 1290)
(constant SQLITE_IOERR_FSTAT 1802)
(constant SQLITE_IOERR_FSYNC 1034)
(constant SQLITE_IOERR_GETTEMPPATH 6410)
(constant SQLITE_IOERR_LOCK 3850)
(constant SQLITE_IOERR_MMAP 6154)
(constant SQLITE_IOERR_NOMEM 3082)
(constant SQLITE_IOERR_RDLOCK 2314)
(constant SQLITE_IOERR_READ 266)
(constant SQLITE_IOERR_ROLLBACK_ATOMIC 7946)
(constant SQLITE_IOERR_SEEK 5642)
(constant SQLITE_IOERR_SHMLOCK 5130)
(constant SQLITE_IOERR_SHMMAP 5386)
(constant SQLITE_IOERR_SHMOPEN 4618)
(constant SQLITE_IOERR_SHMSIZE 4874)
(constant SQLITE_IOERR_SHORT_READ 522)
(constant SQLITE_IOERR_TRUNCATE 1546)
(constant SQLITE_IOERR_UNLOCK 2058)
(constant SQLITE_IOERR_VNODE 6922)
(constant SQLITE_IOERR_WRITE 778)
(constant SQLITE_LOCKED_SHAREDCACHE 262)
(constant SQLITE_LOCKED_VTAB 518)
(constant SQLITE_NOTICE_RECOVER_ROLLBACK 539)
(constant SQLITE_NOTICE_RECOVER_WAL 283)
(constant SQLITE_OK_LOAD_PERMANENTLY 256)
(constant SQLITE_READONLY_CANTINIT 1288)
(constant SQLITE_READONLY_CANTLOCK 520)
(constant SQLITE_READONLY_DBMOVED 1032)
(constant SQLITE_READONLY_DIRECTORY 1544)
(constant SQLITE_READONLY_RECOVERY 264)
(constant SQLITE_READONLY_ROLLBACK 776)
(constant SQLITE_WARNING_AUTOINDEX 284)
(call-constant sqlite3_errstr SQLITE_ABORT_ROLLBACK "abort due to ROLLBACK")
(call-constant sqlite3_errstr SQLITE_AUTH_USER "authorization denied")
(call-constant sqlite3_errstr SQLITE_BUSY_RECOVERY "database is locked")
(call-constant sqlite3_errstr SQLITE_BUSY_SNAPSHOT "database is locked")
(call-constant sqlite3_errstr SQLITE_CANTOPEN_CONVPATH "unable to open database file")
(call-constant sqlite3_errstr SQLITE_CANTOPEN_DIRTYWAL "unable to open database file")
(call-constant sqlite3_errstr SQLITE_CANTOPEN_FULLPATH "unable to open database file")
(call-constant sqlite3_errstr SQLITE_CANTOPEN_ISDIR "unable to open database file")
(call-constant sqlite3_errstr SQLITE_CANTOPEN_NOTEMPDIR "unable to open database file")
(call-constant sqlite3_errstr SQLITE_CONSTRAINT_CHECK "constraint failed")
(call-constant sqlite3_errstr SQLITE_CONSTRAINT_COMMITHOOK "constraint failed")
(call-constant sqlite3_errstr SQLITE_CONSTRAINT_FOREIGNKEY "constraint failed")
(call-constant sqlite3_errstr SQLITE_CONSTRAINT_FUNCTION "constraint failed")
(call-constant sqlite3_errstr SQLITE_CONSTRAINT_NOTNULL "constraint failed")
(call-constant sqlite3_errstr SQLITE_CONSTRAINT_PRIMARYKEY "constraint failed")
(call-constant sqlite3_errstr SQLITE_CONSTRAINT_ROWID "constraint failed")
(call-constant sqlite3_errstr SQLITE_CONSTRAINT_TRIGGER "constraint failed")
(call-constant sqlite3_errstr SQLITE_CONSTRAINT_UNIQUE "constraint failed")
(call-constant sqlite3_errstr SQLITE_CONSTRAINT_VTAB "constraint failed")
(call-constant sqlite3_errstr SQLITE_CORRUPT_SEQUENCE "database disk image is malformed")
(call-constant sqlite3_errstr SQLITE_CORRUPT_VTAB "database disk image is malformed")
(call-constant sqlite3_errstr SQLITE_ERROR_MISSING_COLLSEQ "SQL logic error")
(call-constant sqlite3_errstr SQLITE_ERROR_RETRY "SQL logic error")
(call-constant sqlite3_errstr SQLITE_ERROR_SNAPSHOT "SQL logic error")
(call-constant sqlite3_errstr SQLITE_IOERR_ACCESS "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_AUTH "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_BEGIN_ATOMIC "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_BLOCKED "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_CHECKRESERVEDLOCK "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_CLOSE "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_COMMIT_ATOMIC "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_CONVPATH "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_DELETE "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_DELETE_NOENT "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_DIR_CLOSE "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_DIR_FSYNC "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_FSTAT "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_FSYNC "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_GETTEMPPATH "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_LOCK "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_MMAP "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_NOMEM "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_RDLOCK "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_READ "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_ROLLBACK_ATOMIC "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_SEEK "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_SHMLOCK "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_SHMMAP "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_SHMOPEN "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_SHMSIZE "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_SHORT_READ "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_TRUNCATE "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_UNLOCK "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_VNODE "disk I/O error")
(call-constant sqlite3_errstr SQLITE_IOERR_WRITE "disk I/O error")
(call-constant sqlite3_errstr SQLITE_LOCKED_SHAREDCACHE "database table is locked")
(call-constant sqlite3_errstr SQLITE_LOCKED_VTAB "database table is locked")
(call-constant sqlite3_errstr SQLITE_NOTICE_RECOVER_ROLLBACK "notification message")
(call-constant sqlite3_errstr SQLITE_NOTICE_RECOVER_WAL "notification message")
(call-constant sqlite3_errstr SQLITE_OK_LOAD_PERMANENTLY "not an error")
(call-constant sqlite3_errstr SQLITE_READONLY_CANTINIT "attempt to write a readonly database")
(call-constant sqlite3_errstr SQLITE_READONLY_CANTLOCK "attempt to write a readonly database")
(call-constant sqlite3_errstr SQLITE_READONLY_DBMOVED "attempt to write a readonly database")
(call-constant sqlite3_errstr SQLITE_READONLY_DIRECTORY "attempt to write a readonly database")
(call-constant sqlite3_errstr SQLITE_READONLY_RECOVERY "attempt to write a readonly database")
(call-constant sqlite3_errstr SQLITE_READONLY_ROLLBACK "attempt to write a readonly database")
(call-constant sqlite3_errstr SQLITE_WARNING_AUTOINDEX "warning message")
