(constant OV_FALSE -1)
(constant OV_EOF -2)
(constant OV_HOLE -3)
(constant OV_EREAD -128)
(constant OV_EFAULT -129)
(constant OV_EIMPL -130)
(constant OV_EINVAL -131)
(constant OV_ENOTVORBIS -132)
(constant OV_EBADHEADER -133)
(constant OV_EVERSION -134)
(constant OV_ENOTAUDIO -135)
(constant OV_EBADPACKET -136)
(constant OV_EBADLINK -137)
(constant OV_ENOSEEK -138)
(type-size vorbis_comment 32)
(slot-offs vorbis_comment user_comments 0)
(slot-size vorbis_comment user_comments 8)
(slot-offs vorbis_comment comment_lengths 8)
(slot-size vorbis_comment comment_lengths 8)
(slot-offs vorbis_comment comments 16)
(slot-size vorbis_comment comments 4)
(slot-offs vorbis_comment vendor 24)
(slot-size vorbis_comment vendor 8)
