(constant CWBackPixmap 1)
(constant CWBackPixel 2)
(constant CWBorderPixmap 4)
(constant CWBorderPixel 8)
(constant CWBitGravity 16)
(constant CWWinGravity 32)
(constant CWBackingStore 64)
(constant CWBackingPlanes 128)
(constant CWBackingPixel 256)
(constant CWOverrideRedirect 512)
(constant CWSaveUnder 1024)
(constant CWEventMask 2048)
(constant CWDontPropagate 4096)
(constant CWColormap 8192)
(constant CWCursor 16384)
(type-size XSetWindowAttributes 112)
(slot-offs XSetWindowAttributes background_pixmap 0)
(slot-size XSetWindowAttributes background_pixmap 8)
(slot-offs XSetWindowAttributes background_pixel 8)
(slot-size XSetWindowAttributes background_pixel 8)
(slot-offs XSetWindowAttributes border_pixmap 16)
(slot-size XSetWindowAttributes border_pixmap 8)
(slot-offs XSetWindowAttributes border_pixel 24)
(slot-size XSetWindowAttributes border_pixel 8)
(slot-offs XSetWindowAttributes bit_gravity 32)
(slot-size XSetWindowAttributes bit_gravity 4)
(slot-offs XSetWindowAttributes win_gravity 36)
(slot-size XSetWindowAttributes win_gravity 4)
(slot-offs XSetWindowAttributes backing_store 40)
(slot-size XSetWindowAttributes backing_store 4)
(slot-offs XSetWindowAttributes backing_planes 48)
(slot-size XSetWindowAttributes backing_planes 8)
(slot-offs XSetWindowAttributes backing_pixel 56)
(slot-size XSetWindowAttributes backing_pixel 8)
(slot-offs XSetWindowAttributes save_under 64)
(slot-size XSetWindowAttributes save_under 4)
(slot-offs XSetWindowAttributes event_mask 72)
(slot-size XSetWindowAttributes event_mask 8)
(slot-offs XSetWindowAttributes do_not_propagate_mask 80)
(slot-size XSetWindowAttributes do_not_propagate_mask 8)
(slot-offs XSetWindowAttributes override_redirect 88)
(slot-size XSetWindowAttributes override_redirect 4)
(slot-offs XSetWindowAttributes colormap 96)
(slot-size XSetWindowAttributes colormap 8)
(slot-offs XSetWindowAttributes cursor 104)
(slot-size XSetWindowAttributes cursor 8)
