(include <X11/Xutil.h>)

(constant signed CWBackPixmap)
(constant signed CWBackPixel)
(constant signed CWBorderPixmap)
(constant signed CWBorderPixel)
(constant signed CWBitGravity)
(constant signed CWWinGravity)
(constant signed CWBackingStore)
(constant signed CWBackingPlanes)
(constant signed CWBackingPixel)
(constant signed CWOverrideRedirect)
(constant signed CWSaveUnder)
(constant signed CWEventMask)
(constant signed CWDontPropagate)
(constant signed CWColormap)
(constant signed CWCursor)

(type-size XSetWindowAttributes)
(type-slot XSetWindowAttributes background_pixmap)
(type-slot XSetWindowAttributes background_pixel)
(type-slot XSetWindowAttributes border_pixmap)
(type-slot XSetWindowAttributes border_pixel)
(type-slot XSetWindowAttributes bit_gravity)
(type-slot XSetWindowAttributes win_gravity)
(type-slot XSetWindowAttributes backing_store)
(type-slot XSetWindowAttributes backing_planes)
(type-slot XSetWindowAttributes backing_pixel)
(type-slot XSetWindowAttributes save_under)
(type-slot XSetWindowAttributes event_mask)
(type-slot XSetWindowAttributes do_not_propagate_mask)
(type-slot XSetWindowAttributes override_redirect)
(type-slot XSetWindowAttributes colormap)
(type-slot XSetWindowAttributes cursor)
